### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Germ210** [bv7dev/wgpu-lab#2]
Hello bv7dev, I have contacted you on reddit but in case you did not see, I wish to contribute to the project some time in the future, but instructions are unclear on how to build. I wish to use all extras such as tinyGLTF

**Comment by Germ210** [comment]
Yeah, thank you so much

**Comment by bv7dev** [comment]
Let's have this issue open until the build system has been simplified.

**Comment by Germ210** [comment]
Alright. Maybe adding dawn as a git submodule could make it easier to build

**Comment by bv7dev** [comment]
Maybe. The problem I see is that once you have it as a submodule, it's very difficult to change it later.
At least I had my trouble with submodules in the past.

If we had a simple script to automatically manage dependencies for us, it would be better in my opinion.

**Comment by bv7dev** [comment]
Issue fixed!

CMake now calls `python scripts/lab_fetch_dependencies.py` to download dependencies on configure step.
Static linking is now enabled the default behavior. Could add an option later to build shared
